### ISSUE TITLE
Problem with nested props

### ISSUE THREAD

**Issue by kuatro** [TriPSs/react-esc#18]
For example, we have an API route with a nested array of items and metadata:
```
http://myapi.com/feed

{
    "meta": {
        "has_next": true/false
        "next": "http://myapi.com/feed?from=123456"
    },
    "items": [
        {"id": 1},
        {"id": 2},
        {"id": 3},
    ]
}
```

So our `INITIAL_STATE` looks like this:
```
{
    feed: {
        meta: {},
        items: []
    },
    fetching: false
}
```

And reducer simply applying payload to `feed` piece of state:
```
case Constants.FETCHED_DATA:
      return {
        ...state,
        fetching: false,
        feed: action.payload
      }
```

mapStateToProps:
```
const mapStateToProps = (state) => ({
    feed: state.feed.feed // Looks ugly, but it's just an example
})
```

Resolver:

```
@resolve('feed', (props) => props.fetchData().then(action => action.payload))
```

On `componentWillUnmount` we trigger an action creator which cleans state to initial.

Following this approach, SSE works like a charm. 
But if you try to open the page, then change the location to another path, and then return back – API request will not trigger. Even if we force API request via `componentDidMount` reducer getting correct data, but the data don't appear in the component.

If this case isn't very clear I can make a demo repo.
Thank you in advance!

**Comment by TriPSs** [comment]
I think i know what you mean, this is because `Resolver` also caches the data, i tried it in `react-esc-example` repo and fetched new data in `componentWillMount` then it worked.

Could you try this?

I will look at something to make it optional to cache the result.

**Comment by kuatro** [comment]
@TriPSs Yep. `componentWillMount` triggered API request, reducer got correct data (I can see it via ReduxDevTools), but, for some reason, component got no data.

**Comment by TriPSs** [comment]
@kuatro You can now disable the resolver caching in the following way:
`@resolve('feed', (props) => props.fetchData().then(action => action.payload), false)`
This also means that you are responsible for checking if the action should refetch data, if not then you should return a promise contain the result.

Example:
```Javascript
export function fetchData() {
  return (dispatch, getState) => {
    const cache = Selectors.getJsonPlaceholder(getState())
    if (cache)
      return Promise.resolve(fetchedData(data)

    dispatch(startFetching())

    return fetch('https://jsonplaceholder.typicode.com/posts/1')
      .then(response => response.json())
      .then(data => {
        return dispatch(fetchedData(data))
      })
  }
}
```

Also you have two new global vars available:
`isServer:boolean`
`isClient:boolean` 

And the `Storage.check()` is no longer necessary in your `AppContainer`

P.S. When i disabled the cache i got errors that my client code is not the same as the server code, i will look in to this in the future.

Let me know if this solves you issue.

**Comment by kuatro** [comment]
@TriPSs you rock! Thank you!
