### ISSUE TITLE
Eject functionality

### ISSUE THREAD

**Issue by rkorrelboom** [TriPSs/react-esc#21]
Please provide an eject functionality like React Create App: https://github.com/facebookincubator/create-react-app

**Comment by rkorrelboom** [comment]
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/scripts/eject.js

**Comment by TriPSs** [comment]
[v2.2.0](https://github.com/TriPSs/react-esc/releases/tag/v2.2.0)
