### ISSUE TITLE
Socket.io middleware causing strange problem

### ISSUE THREAD

**Issue by kuatro** [TriPSs/react-esc#23]
export const middlewares = () => {
      const token = Storage.get('cookie', 'token')
      const socket = io(`${SOCKET_IO_URL}/notifications?token=${token}`)
      const socketIOMiddleware = createSocketIoMiddleware(socket)

      return [socketIOMiddleware]
    }

Hi. After applying the code above, I'm getting this error:

    app:esc:server:universal:render   TypeError: Cannot read property 'payload' of undefined
    app:esc:server:universal:render
    app:esc:server:universal:render   - 7.server.js:207
    app:esc:server:universal:render    blah/dist/7.server.js:207:13
    app:esc:server:universal:render
    app:esc:server:universal:render   - next_tick.js:129 process._tickDomainCallback
    app:esc:server:universal:render     internal/process/next_tick.js:129:7
    app:esc:server:universal:render
    app:esc:server:universal:render  +2s

This bug isn't reproducing with `redux-axios-middleware`.

**Comment by TriPSs** [comment]
Could you show what's inside `createSocketIoMiddleware`? Or the lib of it.

**Comment by kuatro** [comment]
@TriPSs It's [redux-socket.io](https://github.com/itaylor/redux-socket.io)

**Comment by TriPSs** [comment]
Could you try it like this:
```Javascript
const token = Storage.get('cookie', 'token')
const socket = io(`${SOCKET_IO_URL}/notifications?token=${token}`)
const socketIOMiddleware = createSocketIoMiddleware(socket)

export const middlewares = () => [
  socketIOMiddleware
]
```

And you do send a `payload` with all of your actions?

**Comment by kuatro** [comment]
The middleware is not working this way.
And yeah, I do send a payload in all of the cases.

I'll try to reproduce the problem using `react-esc-example` repo.

**Comment by TriPSs** [comment]
@kuatro If you could do that would be great. Send me link when you have it up and i will look into it.

**Comment by kuatro** [comment]
@TriPSs Here's the [demo](https://github.com/kuatro/react-esc-example/tree/demo/socket-io-problem)

**Comment by TriPSs** [comment]
@kuatro Thanks for the demo, i created a middleware based on the src from `redux-socket.io`:

File: `SocketIO.js`
``` Javascript
export default function createSocketIoMiddleware(socket, criteria = [], { eventName = 'action', execute = defaultExecute } = {}) {

  const emitBound = socket.emit.bind(socket);

  return ({ dispatch, getState }) => next => action => {
    // Wire socket.io to dispatch actions sent by the server.
    socket.on(eventName, dispatch);
    
    if (evaluate(action, criteria)) {

      execute(action, emitBound, next, dispatch);

    } else {
      return next(action);
    }
  };

  function evaluate(action, option) {
    const { type } = action;
    let matched    = false;
    if (typeof option === 'function') {
      // Test function
      matched = option(type, action);
    } else if (typeof option === 'string') {
      // String prefix
      matched = type.indexOf(option) === 0;
    } else if (Array.isArray(option)) {
      // Array of types
      matched = option.some((item) => type.indexOf(item) === 0);
    }
    return matched;
  }

  function defaultExecute(action, emit, next, dispatch) { // eslint-disable-line no-unused-vars
    emit(eventName, action);

    return next(action);
  }
}
```

Then `reducers.js` will look like this:
``` Javascript
import createSocketIoMiddleware from './SocketIO'
import io from 'socket.io-client'

const SOCKET_IO_URL = 'http://socket.io.server/ws'
const socket = io(`${SOCKET_IO_URL}/notifications?token=123456`)
const socketIOMiddleware = createSocketIoMiddleware(socket)

export const middlewares = () => [
  socketIOMiddleware
]

export default middlewares
```

Could you try this? I did no longer get the error.

**Comment by kuatro** [comment]
@TriPSs  Thanks so much! Everything works fine. The only thing I've changed is this part:

    return ({ dispatch }) => {
        socket.on(eventName, dispatch)

        return next => action => {
            if (evaluate(action, criteria)) {
                execute(action, emitBound, next, dispatch)
            } else {
                return next(action)
            }
        }
    }

Otherwise, it trigger actions 5-6 times at once.

**Comment by TriPSs** [comment]
@kuatro Np, can you close the issue if it's solved?
