### ISSUE TITLE
Custom env variables

### ISSUE THREAD

**Issue by kuatro** [TriPSs/react-esc#28]
Hi! Can't find the way to pass custom environment variables to the app. For example, I want to pass API URL, or something.
Currently, I use `v1`.

**Comment by TriPSs** [comment]
Hello, you can add custom variables to following way:

```js
 custom_globals: {
    __API__: '"http://example.com/v1"',
  },
```

Notice that the string is surrounded with `'` and `"` this is because webpack injects the variable and everything between the  ' ' will be inserted.

**Comment by TriPSs** [comment]
Thanks for pointing it out! Updated the example project with the example:
https://github.com/TriPSs/react-esc-example/blob/master/config/index.js#L106

Can you close the issue if this solves your problem?

**Comment by kuatro** [comment]
Thank you.
Sure, I'll close the issue once I check how it works for me.

**Comment by kuatro** [comment]
So, when I pass a string, it works well.
But when I'm trying to do something like `__MY_ENV__: "process.env.MY_ENV"` it returns correct value at server-side, and `Uncaught ReferenceError: process is not defined` at client-side. I'm just looking for the way to constantize env variables.

**Comment by TriPSs** [comment]
Could you try following ways:

```js
custom_globals: {
       __MY_ENV__   : '"' + process.env.MY_ENV + '"',
       __MY_ENV__2 : process.env.MY_ENV,
}
```

In `__MY_ENV__2` give it as a string to the process like:
package.json
```json
"start": {
      "command": "babel-node bin/server",
      "env": {
        "__MY_ENV__2": "'local'",
      }
}
```

**Comment by kuatro** [comment]
package.json:
```
"start:dev": {
      "command": "babel-node bin/server",
      "env": {
        "__MY_ENV__": "test",
        "__MY_ENV__2": "'local'",
        "NODE_ENV": "development",
        "DEBUG": "app:*"
      }
    },
```

config.js:
```
custom_globals: {
    __MY_ENV__   : '"' + process.env.MY_ENV + '"',
    __MY_ENV__2 : process.env.MY_ENV
  },
```

Output:
```
__MY_ENV__:  undefined
__MY_ENV_2__:  undefined
```

:(

**Comment by kuatro** [comment]
Ooops, wait

**Comment by kuatro** [comment]
Well, `__MY_ENV__   : '"' + process.env.MY_ENV + '"',` works exactly as I expected.
Thank you!

**Comment by kuatro** [comment]
An interesting thing is this approach doesn't work in the production environment, which I run like:
```
npm run deploy:prod
npm run start:prod
```

**Comment by TriPSs** [comment]
@kuatro Maybe a stupid question but just te be sure, MY_ENV is set when running in production?

**Comment by kuatro** [comment]
Sure
```
"start:dev": {
      "command": "babel-node bin/server",
      "env": {
        "MY_ENV": "test",
        "NODE_ENV": "development",
        "DEBUG": "app:*"
      }
    },
    "start:prod": {
      "command": "babel-node bin/server",
      "env": {
        "MY_ENV": "test",
        "NODE_ENV": "production",
        "DEBUG": "app:*"
      }
    },
```

**Comment by TriPSs** [comment]
Do you also have it in the `deploy` part of prod?

Because all the code is rendered to `server.js` for prod the deploy process needs the var to.

**Comment by kuatro** [comment]
@TriPSs Exactly! Thanks!
